apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy-pihole
  name: oauth2-proxy-pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy-pihole
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy-pihole
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=*
        - --github-user="tinoschroeter"
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        # Register a new application
        # https://github.com/settings/applications/new
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: clientid
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: clientsecret
        #docker run -it --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: cookiesecret
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.2-arm64
        imagePullPolicy: Always
        name: oauth2-proxy-pihole
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy-pihole
  name: oauth2-proxy-pihole
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy-pihole
