apiVersion: v1
kind: Service
metadata:
  namespace: pi-hole
  name: pihole-service
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - protocol: UDP 
      name: dns-udp
      port: 53
  externalIPs:
    - 10.0.1.242
---
apiVersion: v1
kind: Service
metadata:
  namespace: pi-hole
  name: pihole-frontend-service
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: pi-hole
  name: pihole-exporter-service
  labels:
    k8s-app: pihole-exporter-service
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - name: http-metrics
      port: 9617
      protocol: TCP
      targetPort: 9617 
